export const QUERYGOODS_SET_GOODS = "QUERYGOODS_SET_GOODS";
export const QUERYGOODS_SET_SEARCH_KEY = "QUERYGOODS_SET_SEARCH_KEY";
export const QUERYGOODS_SET_TOGGLE_BRAND = "QUERYGOODS_SET_TOGGLE_BRAND";
export const QUERYGOODS_SET_TOGGLE_BRAND_BATCH = "QUERYGOODS_SET_TOGGLE_BRAND_BATCH";

export const QUERYGOODS_SET_TOGGLE_CATEGORY = "QUERYGOODS_SET_TOGGLE_CATEGORY";
export const QUERYGOODS_SET_TOGGLE_CATEGORY_BATCH = "QUERYGOODS_SET_TOGGLE_CATEGORY_BATCH"
export const QUERYGOODS_SET_CHECKED_CATEGORY = "QUERYGOODS_SET_CHECKED_CATEGORY"

export const QUERYGOODS_SET_SELECTED_TIME_RANGE = "QUERYGOODS_SET_SELECTED_TIME_RANGE";
export const QUERYGOODS_DELETE_REFINE_BY = "QUERYGOODS_DELETE_REFINE_BY";
export const QUERYGOODS_SET_SORTER = "QUERYGOODS_SET_SORTER";

export const QUERYGOODS_SET_BRANDS = "QUERYGOODS_SET_BRANDS"
export const QUERYGOODS_SET_CATEGORIES = "QUERYGOODS_SET_CATEGORIES"
export const QUERYGOODS_RESET_ALL_BRANDS = "QUERYGOODS_RESET_ALL_BRANDS"
export const QUERYGOODS_RESET_ALL_CATEGORIES = "QUERYGOODS_RESET_ALL_CATEGORIES"
export const QUERYGOODS_SET_CHECKED_BRANDS = "QUERYGOODS_SET_CHECKED_BRANDS"

export const QUERYGOODS_ADD_TO_CART = "QUERYGOODS_ADD_TO_CART";
export const QUERYGOODS_DELETE_FROM_CART = "QUERYGOODS_DELETE_FROM_CART";
export const QUERYGOODS_MODIFY_QUANTITY = "QUERYGOODS_MODIFY_QUANTITY";
export const QUERYGOODS_BY_PAGINATION = "QUERYGOODS_BY_PAGINATION";